import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useContext, useEffect, useState } from 'react';

import CalendarHeader from '../components/CalendarHeader';
import Month from '../components/Month';
import Sidebar from '../components/Sidebar';
import GlobalContext from '../context/GlobalContext';
import styles from '../styles/Home.module.css';
import { getMonth } from '../utils/day';

const Home: NextPage = () => {
  console.table(getMonth());
  const [currentMonth, setCurrentMonth] = useState(getMonth());

  const { monthIndex } = useContext(GlobalContext);

  useEffect(() => {
    setCurrentMonth(getMonth(monthIndex));
  }, [monthIndex]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen flex flex-col">
        <CalendarHeader />
        <div className="flex flex-1">
          <Sidebar />
          <Month month={currentMonth} />
        </div>
      </div>
    </div>
  );
};

export default Home;
