import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';

import CalendarHeader from '../components/CalendarHeader';
import Month from '../components/Month';
import Sidebar from '../components/SIdebar';
import styles from '../styles/Home.module.css';
import { getMonth } from '../utils/day';

const Home: NextPage = () => {
  console.table(getMonth());
  const [currentMonth, setCurrentMonth] = useState(getMonth());
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <div className="h-screen flex flex-col">
        <CalendarHeader />
        <div className="flex flex-1">
          <Sidebar />
          <Month month={currentMonth} />
        </div>
      </div>
    </div>
  );
};

export default Home;
